theme = "hugo-narrow"
Title = "MERL @ Rose-Hulman"

[params]

  [params.colorScheme]
  [params.colorScheme.themes]
    [params.colorScheme.themes.default]
      name = "Default"
      order = "1"
    [params.colorScheme.themes.claude]
      name = "Claude"
      order = "2"

  [params.logo]
    image = "images/avatar.jpeg"
    link = "/"

  [params.site]
    title = "MERL @ Rose-Hulman"
    subtitle = "Multidisciplinary Educational Robotics Lab"
    keywords = ["robotics", "embedded systems", "Multidisciplinary", "Educational", "Rose-Hulman", "MERL"]

  [params.author]
    name = "MERL Team"
    avatar = "images/avatar.jpeg"
    
    description = "MERL develops inclusive, open-source educational robotics platforms like LilyBot and IvyBot, fostering STEM engagement and hands-on learning at Rose-Hulman Institute of Technology, led by Dr. Carlotta A. Berry."
    email = "merl.rose.hulman@gmail.com"
    instagram = "noiresteminist"
    website = "https://noiresteminist.com"
    githubUsername = "MERL-Rose-Hulman"

    [[params.author.social]]
      name = "GitHub"
      icon = "github"
      url = "https://github.com/MERL-Rose-Hulman"

    [[params.author.social]]
      name = "Instagram"
      icon = "Instagram"
      url = "https://instagram.com/noiresteminist"

  [params.projects]
    [[params.projects.list]]
      name = "LilyBotCommon"
      description = "Common firmware and interface libraries for LilyBot"
      repo = "https://github.com/MERL-Rose-Hulman/LilyBotCommon"
    


[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3
