name: Build & Deploy Hugo site to Pages
on:
  push:
    branches: [ deployment ]        # publish only from deployment branch
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      # keeps submodule & depth options
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3   # unchanged
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build site
        run: hugo --minify -s merl-site -d public
      - name: 📦 Upload site artifact        # ★ updated line
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: 🚀 Deploy to GitHub Pages      # ★ updated line
        id: deployment
        uses: actions/deploy-pages@v4